Add missing # to survey template
Smarty complained:

    User Error: Smarty error: [in survey/show_root.tpl line 39]: syntax
    error: unidentified token '::MODE_ALL'

PHP constants need to be used with # signs.